clash.postgres.hostname: dbis-exp1
clash.postgres.db_name: tpch-sf1

clash.controller.enabled: false

clash.reporter.parallelism: 1
clash.reporter.type: Influx
clash.reporter.postgres.hostname: "dbis-exp1"
clash.reporter.postgres.port: "5432"
clash.reporter.postgres.db_name: "clash-test"
clash.reporter.postgres.user: "clash"
clash.reporter.postgres.password: "clash"

clash.probe_log.enabled: false

clash.influx.url: "http://localhost:8086"
clash.influx.username: clash
clash.influx.password: clash
clash.influx.db_name: clash-metrics

