image: openjdk:11

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

stages:
  - test

lint:
  stage: test
  script:
    - ./gradlew check

tests:
  stage: test
  script:
    - ./gradlew test